### ISSUE TITLE
group download

### ISSUE THREAD

**Issue by freehussain** [tanoDxyz/GDownload#1]
hello,

how can i get the list of group download?

**Comment by tanoDxyz** [comment]
Checkout `GroupListener` it has different methods.

also you can get list of downloads by calling `Group.getState()`.
` Group.getState()`.

will return different type of lists of downloads.

            downloads,
            queuedDownloads,
            pausedDownloads,
            runningDownloads,
            completedDownloads,
            cancelledDownloads,
            failedDownloads,

**Comment by freehussain** [comment]
i'm trying to download 114 file, but it looks that max number is 30 or more, can you please confirm the max number of files, and if you can limit download for 2 urls only

**Comment by tanoDxyz** [comment]
there is a field
concurrentDownloadsRunningCapacity

which is used to handle number of concurrent downloads that can run at same time.
please check the documentation.
 👇

**Group Downloads**

**Comment by freehussain** [comment]
thanks it works
