### ISSUE TITLE
Group downlaod

### ISSUE THREAD

**Issue by freehussain** [tanoDxyz/GDownload#10]
Group downlaod lifecycle destroy on activity destroy, is there  a way to make it like service or worker?

**Comment by tanoDxyz** [comment]
avoid passing lifecycle.
instead use application context.

Group downloader will not be destroyed.

and currently if you run group downloader in foreground service.
it will work.

currently there is no such implementation
and i don't have bandwidth to do that right now.

but i would be happy if you do that by making PR

**Comment by freehussain** [comment]
But In your example it needs lifecycle, I can't pass context, 

Is there a way to build lifecycle with app context?

**Comment by tanoDxyz** [comment]
also if you don't like this way of initialization

GroupDownloadManager 
has Builder too.

**Comment by freehussain** [comment]
Thanks it works
