### ISSUE TITLE
get group download to cancel it

### ISSUE THREAD

**Issue by freehussain** [tanoDxyz/GDownload#11]
if you are downloading in fragment you may close it and come back again, so i need to get the group of downloading to cancel if the user want to

**Comment by freehussain** [comment]
i tired to use group builder

GroupImpl.Builder(App.INCTANCE)
                .setIdAndName(args.playListId.toLong(), args.title ?: "playlist")
                .setNetworkInfoProvider(NetworkInfoProvider(App.INCTANCE))
                .setConcurrentDownloadsCapacity(1)
                .setGroupLoopTimeMilliSecs(2000)
                .setProgressUpdateTimeMilliSecs(2000)
                .setProgressCallbackLifeCycle(lifecycle)
                .setProgressCallbacksOnMainThread(true)
                .build()

but it always yes create new instance, it should return the current instance based on id

**Comment by tanoDxyz** [comment]
> if you are downloading in fragment you may close it and come back again, so i need to get the group of downloading to cancel if the user want to



are you not able to cancel the download?

or 

download is not canceled even you called 
cancel() function ?

**Comment by freehussain** [comment]
no, i need references to group after losing it ( ex: close activity and back again),

**Comment by freehussain** [comment]
hello

thank you alot, i save id on viewmodel, it works great !!
