### ISSUE TITLE
Documentation request for Java

### ISSUE THREAD

**Issue by devjoseq** [tanoDxyz/GDownload#14]
Hello, is there a document explaining how we can use this library in Java?

**Comment by tanoDxyz** [comment]
I will update it shortly(day/s).

**Comment by devjoseq** [comment]
I'm looking forward to it, thank you for your help

**Comment by tanoDxyz** [comment]
`    public void main(Context context, LifecycleOwner lifecycleOwner) {
        // lifecycle will make ur life cycle harder if you don't know it well.
        // so avoid it
        final boolean downloadCallbacksOnMainThread = true; // false if u want background thread for callbacks
        ScheduledBackgroundExecutorImpl executor = new ScheduledBackgroundExecutorImpl(_Kt.DEF_MAX_THREADS_PER_EXECUTOR, null);

        // if u want download callbacks to invoke on non ui thread. then pass non null BackgroundExecutor but don't touch {executor object} create new one. it's ok...as you may suffer download callbacks due to busy threads.
        DownloadCallbacksHandler downloadCallbacksHandler = new DownloadCallbacksHandler(downloadCallbacksOnMainThread, null, new BackgroundExecutorImpl());

        File directoryWhereYouWantToSaveFiles = null;
        FileStorageHelper storageHelper = new DefaultFileStorageHelper(context);
        if (directoryWhereYouWantToSaveFiles == null) {
            storageHelper.setFilesRootToDownloadsOrFallbackToInternalDirectory();
        } else {
            storageHelper.setFilesRoot(directoryWhereYouWantToSaveFiles);
        }

        Factory<URLConnectionHandler> connectionHandlerFactory = null; // in case u want ur own things.
        ConnectionManager connectionManager = new ConnectionManagerImpl(connectionHandlerFactory == null ? new URLConnectionFactory() : connectionHandlerFactory, executor);

        SQLiteManager databaseManager = SQLiteManager.Companion.getInstance(context);


        NetworkInfoProvider networkInfoProvider = new NetworkInfoProvider(context);
        /**
         * remember you don't need to overload all the methods. just overload what you want.
         */
        DownloadProgressListener downloadProgressListener = new DownloadProgressListener() {
            @Override
            public void onConnectionEstablished(DownloadInfo downloadInfo) {
                DownloadProgressListener.super.onConnectionEstablished(downloadInfo);
                System.out.println("log: Download connection established.");
            }

            @Override
            public void onDownloadProgress(DownloadInfo downloadInfo) {
                DownloadProgressListener.super.onDownloadProgress(downloadInfo);
                System.out.println("log: on Progress "+downloadInfo.getProgress());
            }

            @Override
            public void onDownloadFailed(@NonNull DownloadInfo downloadInfo, @NonNull String ex) {
                DownloadProgressListener.super.onDownloadFailed(downloadInfo, ex);
                System.out.println("log: failed download ->"+ex);
            }

            @Override
            public void onDownloadSuccess(@NonNull DownloadInfo downloadInfo) {
                DownloadProgressListener.super.onDownloadSuccess(downloadInfo);
                System.out.println("marko: file downloaded successfully at ->"+downloadInfo.getFilePath());
            }
        };

        /**
         * Bonus
         * remember progress -1.0 means indeterminate -> downloader unable to determine the total bytes or whatsoever.
         */
        DownloadManager downloadManager = new DownloadManager.Builder(context).
                setCallbacksHandler(downloadCallbacksHandler).
                setDownloadDatabaseManager(databaseManager).
                setConnectionManager(connectionManager).
                setNetworkInfoProvider(networkInfoProvider).
                setStorageHelper(storageHelper).build();
        downloadManager.download("https://github.com/tanoDxyz/GDownload", "heelo.txt", NetworkType.ALL, downloadProgressListener);

    }
`
