### ISSUE TITLE
Manually setting Thread count

### ISSUE THREAD

**Issue by GuilhermePX3** [tanoDxyz/GDownload#15]
Using KT, how to manually set the Threads amout to the downloader?

I am implementing in a case that it will be usefull.

**Comment by GuilhermePX3** [comment]
Great! My doubt is what the reason to use Thread pooling to the download system. Is that the reason to make it faster than other fetch libraries?

If that is the reason, what must happen if the file comes from a limited bandwidth or IP limited servers, that "blocks" simultaneous downloads?

Made a great work so far! I hope to help improve the lib.

**Comment by tanoDxyz** [comment]
yes multiple connections are used to **quickly** download the data.

If someone for example ask **GDownload** to use 40 connection for a download but server does not support such thing - so in this case download will be done in a single connection.
so if a server blocks simultaneous connections. **GDownloads** honors it.

thank you!
