### ISSUE TITLE
Issue while using group

### ISSUE THREAD

**Issue by GuilhermePX3** [tanoDxyz/GDownload#16]
While using group downloader, is there any function that "pauses" current download and "resumes" some of the downloads using it's id?

For example, while downloading large files, the user may want to pause some, just by resuming another. Let's say I have 5 downloads in list, the 2nd is downloading, but for the moment I want to prioritize the 3rd. Then I press resume on 3rd, that "pauses" (and not freezes) the 2nd, making the 3rd a priority.

       private fun createGroupDownloader(callback: (Group) -> Unit) {
            GDownload.freeGroup(context) {
                concurrentDownloadsRunningCapacity = 1 // maximum number of parallel downloads running...
                groupLoopTimeMilliSecs = 2_000
                maxConnectionPerDownload = 32 // max number of connection per download...
                progressCallbacksOnMainThread = true
                val group = getGroup()
                group?.let(callback)
            }
        }

**Comment by GuilhermePX3** [comment]
Would be great too the Download class to have a Custom set ID, which not overrides the main Long ID, but be able to identify a download by the custom. I am currently using shared preferences and ConcurrentHashMap<String, Long> to deal with that

**Comment by tanoDxyz** [comment]
Apologies i was off grid. well get back to u on this shortly.

**Comment by tanoDxyz** [comment]
> While using group downloader, is there any function that "pauses" current download and "resumes" some of the downloads using it's id?
> 
> For example, while downloading large files, the user may want to pause some, just by resuming another. Let's say I have 5 downloads in list, the 2nd is downloading, but for the moment I want to prioritize the 3rd. Then I press resume on 3rd, that "pauses" (and not freezes) the 2nd, making the 3rd a priority.
> 
> ```
>    private fun createGroupDownloader(callback: (Group) -> Unit) {
>         GDownload.freeGroup(context) {
>             concurrentDownloadsRunningCapacity = 1 // maximum number of parallel downloads running...
>             groupLoopTimeMilliSecs = 2_000
>             maxConnectionPerDownload = 32 // max number of connection per download...
>             progressCallbacksOnMainThread = true
>             val group = getGroup()
>             group?.let(callback)
>         }
>     }
> ```

**No Group by default don't support that but we can achieve that manually.**

1.  using Group.freezDownload(downloadId) or stopDownloadId(downloadId) on the downloads that you want to stop and let the one run that you want to prioritize.
2. using Group.stopAll() or freezeAll() and run the one that you want to prioritize.

**Comment by tanoDxyz** [comment]
`Download` class has an **id** field. you can provide your own as well and i believe no one is going to overwrite it but remember the following.

1. Always keep ur id's unique.
