### ISSUE TITLE
Do you plan to support to upload data?

### ISSUE THREAD

**Issue by Zhao-Michael** [tanoDxyz/GDownload#17]
Or Maybe preserve the interface to custom to support upload data.....

BTW, I don't know if support the okhttp3 as the underlying connection handler ...

**Comment by tanoDxyz** [comment]
No current plans for uploading .....
regarding okHttp3 .

- if okHttp3 uses java's default `InputStream/OutputStream` classes than it's super easy to write a custom Connection Handler.
- The library is designed in such a way to modify almost each individual function without affecting others. 

**I will add examples shortly.**

**Comment by Zhao-Michael** [comment]
Hi @tanoDxyz,

I try to add the okhttp3 as the URLConnectionHandler, mostly looks goods.

Expect that data class "RemoteConnection" (https://github.com/tanoDxyz/GDownload/blob/40dddae11544acdbf37ae781cd806c21763bed3b/gdownload/src/main/java/com/tanodxyz/gdownload/connection/RemoteConnection.kt#L9) needs to update:

since okhttp3 didn't have URLConnection (I think....), so "var connection: URLConnection," may change to var connection: URLConnection?, or just a callback like "var disconnect: () -> Unit = {}"

**Comment by tanoDxyz** [comment]
Sorry for late response! very busy these days. 

actually ur right... 

We have to change `java.net.URLConnection `from `RemoteConnection` class.
