### ISSUE TITLE
cancel single download

### ISSUE THREAD

**Issue by freehussain** [tanoDxyz/GDownload#2]
hello,

i can't cancel single download file, can you please help

**Comment by tanoDxyz** [comment]
Hi there !
you can call 
```
downloader.stopDownload {stopped,msg ->
            if(stopped) {
                //download stopped
            }else {
                // $msg indicates the reason
            }
        }
```
also if that is not the case.
please provide some details. 
like logs, stack trace.

**library logs every step of downloading. if something fails or not work as expected you can check the log cat too.**
