### ISSUE TITLE
download json file error

### ISSUE THREAD

**Issue by freehussain** [tanoDxyz/GDownload#3]
hello,

i'm trying to download json file but there are error:

get file length isn't true
downloaded file corrupted 

here is a link for download file example
https://files.goldenquran.org/quraan_tafser/11_v5.json

please also if there a chance i need direct connection with you

**Comment by tanoDxyz** [comment]
first i have checked the file link you provided.

opened it with chrome and edge.
the file is **not valid json file**.
there are a lot of `\u064` Unicode chars.
i would suggest contact the relevant authority or if the file is downloaded 
convert the unicode codepoints to characters.

second you said file length was not true.
library will still download the file.
did your downloaded succeed.

**Comment by freehussain** [comment]
hello,

these characters supposed to be arabic  letters 
please check the image bellow.

before i use your library it was successfully downloaded by the following code

 val request = Request.Builder().url(URL(url)).build() 
 val response = OkHttpClient().newCall(request).execute()

for downloading file it works but downloaded file looks strange, something like binary file
what do you think the issue is?

<img width="1667" alt="Screenshot 2023-03-30 at 6 20 04 AM" src="https://user-images.githubusercontent.com/14986265/228720098-b505d5d3-97c3-438e-860b-fa5c95e2639a.png">

**Comment by tanoDxyz** [comment]
dear if the file contains unicode chars we are good.

if as you mentioned that it looks like binary.

i found the issue 
i will patch some changes shortly and necessary documentation.

it is basically due to extra header that we are sending in request.

**Comment by tanoDxyz** [comment]
ok i found the issue. 
basically by default `accept-encoding` header was sent with request body and that was causing the problem.
and i updated the repo via  quick patch.

you can try  
 `implementation 'com.github.tanoDxyz:GDownload:1.1'`

thank you so much.

**Comment by freehussain** [comment]
thank you alot for your kindness, it works now

please give me your phone number or twitter, we may have a good chance for job

**Comment by tanoDxyz** [comment]
Skype = 

**s.tanveer.h**
